packages:
  - apps/**
  - packages/**

catalog:
  '@base-ui/react': ^1.0.0
  '@eslint/js': ^9.39.2
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^25.0.5
  '@types/react': ^19.2.7
  class-variance-authority: ^0.7.1
  eslint: ^9.39.2
  eslint-config-next: ^16.1.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  lucide-react: ^0.562.0
  next: ^16.1.1
  next-globe-gen: ^1.9.3
  next-themes: ^0.4.6
  postcss: ^8.5.6
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.52.0

catalogMode: strict

minimumReleaseAge: 0

resolutionMode: lowest-direct
